AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
    - Rakefile
    - gruf-sentry.gemspec
plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety


# Allow *VALID_CONFIG_KEYS.keys
Lint/AmbiguousOperator:
  Exclude:
    - lib/gruf/sentry/configuration.rb

# This cop conflicts with other cops
Layout/LineLength:
  Max: 140

Metrics/AbcSize:
  Max: 147

Metrics/MethodLength:
  Max: 88

Metrics/ModuleLength:
  Max: 1000

Metrics/ParameterLists:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 12

Naming/FileName:
  Exclude:
    - lib/gruf-sentry.rb
